In [53]:
import librosa
import numpy as np
import soundfile as sf
from sklearn.linear_model import LinearRegression

In [69]:
#load file
#pad signal
#extract log spectrogram from signal
#normalize spectrogram
#save normalized spectrogram
#Probably very helpful yt tutorial:
#https://www.youtube.com/watch?v=Ey8IZQl_lKs&list=PL-wATfeyAMNpEyENTc-tVH5tfLGKtSWPp&index=1
#also this
#https://www.youtube.com/watch?v=umAXGVzVvwQ
#this guy has a lot of videos on audio AI stuff
#number audio -> number audio

=========================

messing with stuff below:

=========================

In [61]:
y1,sr1 = librosa.load('synthesizef.wav')
y2,sr2 = librosa.load('synthesizem.wav')

In [62]:
y2

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [63]:
if(len(y1)<len(y2)):
    y1=np.concatenate([y1, np.zeros(len(y2)-len(y1))])
else:
     y2=np.concatenate([y2, np.zeros(len(y1)-len(y2))])

In [64]:
#obviously don't do this but I just wanted to put something down lol
reg = LinearRegression()
reg.fit(y1.reshape(-1, 1),y2.reshape(-1, 1))

LinearRegression()

In [65]:
result = reg.predict(y1.reshape(-1, 1))

In [66]:
sf.write('file_trim_5s.wav', result, sr2)

In [67]:
result[10:1000]

array([[-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10866113e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10866113e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10864894e-05],
       [-3.10864894e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10864894e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.10863674e-05],
       [-3.1

In [68]:
y1[10:1000]

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -3.72529030e-09,  0.00000000e+00,  0.00000000e+00,
       -3.72529030e-09, -3.72529030e-09, -3.72529030e-09, -3.72529030e-09,
       -3.72529030e-09, -3.72529030e-09, -3.72529030e-09,  0.00000000e+00,
        0.00000000e+00, -3.72529030e-09, -3.72529030e-09, -3.72529030e-09,
        0.00000000e+00,  0.00000000e+00,  3.72529030e-09,  3.72529030e-09,
        0.00000000e+00,  0.00000000e+00,  3.72529030e-09,  3.72529030e-09,
        3.72529030e-09,  3.72529030e-09,  3.72529030e-09,  3.72529030e-09,
        3.72529030e-09,  0.00000000e+00,  3.72529030e-09,  3.72529030e-09,
        3.72529030e-09,  3.72529030e-09,  0.00000000e+00, -3.72529030e-09,
       -3.72529030e-09, -3.72529030e-09, -3.72529030e-09,  0.00000000e+00,
       -3.72529030e-09, -3.72529030e-09, -3.72529030e-09, -3.72529030e-09,
        0.00000000e+00, -3.72529030e-09, -3.72529030e-09, -7.45058060e-09,
       -7.45058060e-09, -